language: node_js
notifications:
  email: false
node_js:
  - "4.1"
  - "4.0"
before_install:
  - npm install npm
  - npm install -g gulp@3.9
install:
  - npm install
  - gulp bower
script:
  - gulp db
  - gulp tests
