addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libelfg0
      - libstdc++6
language: node_js
notifications:
  email: false
node_js:
  - "5"
#  - "5.3"
#  - "5.2"
#  - "4"
#  - "4.2"
#  - "0.12"
  - "0.10"
before_install:
  - npm install -g gulp@3.9
  - install/install.sh
  - source install/env.sh
install:
  - git lfs fetch
  - git lfs checkout
  - npm install
  - gulp bower
script:
  - ( cd examples && make )
  - mv examples/*.db import/
  - gulp db
  - mv data/*.db import/
  - gulp db
  - gulp tests
