language: node_js
notifications:
  email: false
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
before_install:
  - npm install -g gulp@3.9
  - mkdir -p $HOME/bin/$HOME/bin/
  - wget https://github.com/github/git-lfs/releases/download/v1.0.1/git-lfs-linux-amd64-1.0.1.tar.gz
  - tar xvfz git-lfs-linux-amd64-1.0.1.tar.gz
  - mv git-lfs-1.0.1/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/
install:
  - git lfs fetch
  - git lfs checkout
  - npm install
  - gulp bower
script:
  - cp examples/*.db import/
  - gulp db
  - mv data/*.db import/
  - gulp db
  - gulp tests
