CREATE INDEX IF NOT EXISTS ACCESS_TABLE_ID ON Access(Id);
CREATE INDEX IF NOT EXISTS FILE_TABLE_ID ON File(Id);
CREATE INDEX IF NOT EXISTS INSTRUCTION_TABLE_ID ON Instruction(Id);
CREATE INDEX IF NOT EXISTS REFERENCE_TABLE_ID ON Reference(Id);
CREATE INDEX IF NOT EXISTS SEGMENT_TABLE_ID ON Segment(Id);
CREATE INDEX IF NOT EXISTS THREAD_TABLE_ID ON Thread(Id);

CREATE INDEX IF NOT EXISTS ACCESS_TABLE_INSTRUCTION ON Access(Instruction);
CREATE INDEX IF NOT EXISTS ACCESS_TABLE_REFERENCE ON Access(Reference);

CREATE INDEX IF NOT EXISTS INSTRUCTION_TABLE_SEGMENT ON Instruction(Segment);

CREATE INDEX IF NOT EXISTS REFERENCE_TABLE_ALLOCATOR ON Reference(Allocator);

CREATE INDEX IF NOT EXISTS SEGMENT_TABLE_CALL ON Segment(Call);
CREATE INDEX IF NOT EXISTS SEGMENT_TABLE_LOOP ON Segment(LoopIteration);

CREATE INDEX IF NOT EXISTS THREAD_TABLE_CREATE_INSTRUCTION ON Thread(CreateInstruction);
CREATE INDEX IF NOT EXISTS THREAD_TABLE_JOIN_INSTRUCTION ON Thread(JoinInstruction);

CREATE INDEX IF NOT EXISTS INSTRUCTION_TAG_INSTANCE_TABLE_INSTRUCTION ON InstructionTagInstance(Instruction);
CREATE INDEX IF NOT EXISTS INSTRUCTION_TAG_INSTANCE_TABLE_TAG ON InstructionTagInstance(Tag);

CREATE INDEX IF NOT EXISTS TAG_INSTANCE_TABLE_START ON TagInstance(Start);
CREATE INDEX IF NOT EXISTS TAG_INSTANCE_TABLE_END ON TagInstance(End);
