ALTER TABLE LoopExecution RENAME TO Temporary;
CREATE TABLE "LoopExecution"(
  Id INT PRIMARY KEY NOT NULL,
  Loop INT NOT NULL,
  Parent INT,
  Duration INT,
  Call INT
);
INSERT INTO LoopExecution SELECT
  Id,
  Loop,
  Parent,
  Duration,
  (SELECT c.Id FROM Call c, Segment s, LoopIteration i WHERE c.Id = s.Call AND s.Id = i.Segment)
AS CALL FROM Temporary;
DROP TABLE Temporary;

CREATE INDEX IF NOT EXISTS LOOP_TABLE_ID ON Loop(No);
CREATE INDEX IF NOT EXISTS LOOP_EXECUTION_TABLE_ID ON LoopExecution(Id);
CREATE INDEX IF NOT EXISTS LOOP_ITERATION_TABLE_ID ON LoopIteration(Id);

CREATE INDEX IF NOT EXISTS LOOP_EXECUTION_TABLE_CALL ON LoopExecution(Call);
CREATE INDEX IF NOT EXISTS LOOP_EXECUTION_TABLE_PARENT ON LoopExecution(Parent);
CREATE INDEX IF NOT EXISTS LOOP_EXECUTION_TABLE_LOOP ON LoopExecution(Loop);

CREATE INDEX IF NOT EXISTS LOOP_ITERATION_TABLE_EXECUTION ON LoopIteration(Execution);
CREATE INDEX IF NOT EXISTS LOOP_ITERATION_TABLE_SEGMENT ON LoopIteration(Segment);
